<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
    'key' => 'group_555a2ef138016',
    'title' => 'Events Index',
    'fields' => array (
        array (
            'key' => 'field_555a2efc1ee80',
            'label' => 'Index Sidebar Type',
            'name' => 'index_sidebar_type',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array (
                'link-lists' => 'Link List(s)',
                'event-spotlight' => 'Event Spotlight',
            ),
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => 'link-lists',
            'layout' => 'vertical',
        ),
        array (
            'key' => 'field_555a301cb7887',
            'label' => 'Box Heading',
            'name' => 'index_sidebar_box_heading',
            'type' => 'text',
            'instructions' => 'Small heading to contextualize the box. Example: "Next Info Session"',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_555a2efc1ee80',
                        'operator' => '==',
                        'value' => 'event-spotlight',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_555a3191b788a',
            'label' => 'Image',
            'name' => 'index_sidebar_image',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_555a2efc1ee80',
                        'operator' => '==',
                        'value' => 'event-spotlight',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'id',
            'preview_size' => 'img_220',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array (
            'key' => 'field_555a309cb7888',
            'label' => 'Main Heading',
            'name' => 'index_sidebar_main_heading',
            'type' => 'text',
            'instructions' => 'Primary heading for your main content.',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_555a2efc1ee80',
                        'operator' => '==',
                        'value' => 'event-spotlight',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_555a30c6b7889',
            'label' => 'Text',
            'name' => 'index_sidebar_text',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_555a2efc1ee80',
                        'operator' => '==',
                        'value' => 'event-spotlight',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => '',
            'new_lines' => 'br',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_555a3277b788b',
            'label' => 'Call to Action',
            'name' => 'index_sidebar_call_to_action',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_555a2efc1ee80',
                        'operator' => '==',
                        'value' => 'event-spotlight',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_555a328ab788d',
            'label' => 'URL',
            'name' => 'index_sidebar_url',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_555a2efc1ee80',
                        'operator' => '==',
                        'value' => 'event-spotlight',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'http://',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_555a3db80712c',
            'label' => 'Lists',
            'name' => 'lists',
            'type' => 'flexible_content',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_555a2efc1ee80',
                        'operator' => '==',
                        'value' => 'link-lists',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'button_label' => 'Add List',
            'min' => 1,
            'max' => '',
            'layouts' => array (
                array (
                    'key' => '555a3de035aff',
                    'name' => 'sub-calendars',
                    'label' => 'Sub-Calendars',
                    'display' => 'block',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_555a3df40712d',
                            'label' => 'Heading',
                            'name' => 'heading',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 'Sub-Calendars',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                    ),
                    'min' => 0,
                    'max' => 1,
                ),
                array (
                    'key' => '555a3e210712e',
                    'name' => 'custom_list',
                    'label' => 'Custom List',
                    'display' => 'block',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_555a3e420712f',
                            'label' => 'Heading',
                            'name' => 'heading',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        array (
                            'key' => 'field_555a3e6707130',
                            'label' => 'Content',
                            'name' => 'content',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'min' => '',
                            'max' => '',
                            'layout' => 'table',
                            'button_label' => 'Add Row',
                            'sub_fields' => array (
                                array (
                                    'key' => 'field_555a3e7e07131',
                                    'label' => 'Text',
                                    'name' => 'text',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                    'readonly' => 0,
                                    'disabled' => 0,
                                ),
                                array (
                                    'key' => 'field_555a3e9707132',
                                    'label' => 'URL',
                                    'name' => 'url',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => 'http://',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                    'readonly' => 0,
                                    'disabled' => 0,
                                ),
                            ),
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
            ),
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'acf-options-index-settings',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
));

endif;

?>