<?php

if( function_exists('register_field_group') ):

register_field_group(array (
	'key' => 'group_548b51c21f4db',
	'title' => 'Featured Video',
	'fields' => array (
		array (
			'key' => 'field_53849a0043c39',
			'label' => 'Video ID',
			'name' => 'video_id',
			'prefix' => '',
			'type' => 'text',
			'instructions' => 'Overrides Featured Image.

Paste the ID of the YouTube video you would like to embed. 

You can find the ID on YouTube by clicking "Share".	 The ID is everything that comes after "http://youtu.be/".	 For example, the ID of http://youtu.be/zmx_RF-4aII is "zmx_RF-4aII".',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'none',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
	),
));

register_field_group(array (
	'key' => 'group_548b51c231cf8',
	'title' => 'Home Page',
	'fields' => array (
		array (
			'key' => 'field_5375275d6e138',
			'label' => 'Banner',
			'name' => 'banner',
			'prefix' => '',
			'type' => 'repeater',
			'instructions' => 'Main image area at top of homepage below site name and logo.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'row_min' => 1,
			'row_limit' => 1,
			'layout' => 'row',
			'button_label' => 'Add Row',
			'min' => 0,
			'max' => 0,
			'sub_fields' => array (
				array (
					'key' => 'field_53762d3833cf3',
					'label' => 'Image',
					'name' => 'image',
					'prefix' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'return_format' => 'array',
				),
				array (
					'key' => 'field_53762f16486da',
					'label' => 'Headline',
					'name' => 'headline',
					'prefix' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_53762e5f486d9',
					'label' => 'Sub Heading',
					'name' => 'sub_heading',
					'prefix' => '',
					'type' => 'text',
					'instructions' => 'Appears above the headline as a pseudo-heading',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_53762f49486db',
					'label' => 'Link To',
					'name' => 'link_to',
					'prefix' => '',
					'type' => 'text',
					'instructions' => 'Banner link destination URL',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'http://',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_537b9b6d6c65c',
					'label' => 'Sidebar',
					'name' => 'sidebar',
					'prefix' => '',
					'type' => 'true_false',
					'instructions' => 'Display a sidebar of events or an rss feed',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Show sidebar',
					'default_value' => 0,
				),
				array (
					'key' => 'field_537b9b8d6c65d',
					'label' => 'Sidebar Type',
					'name' => 'sidebar_type',
					'prefix' => '',
					'type' => 'radio',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_537b9b6d6c65c',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'events' => 'Events',
						'rss' => 'Story Feed',
					),
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
				),
				array (
					'key' => 'field_537b9bf99bab0',
					'label' => 'Sidebar Settings',
					'name' => 'sidebar_settings',
					'prefix' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_537b9b6d6c65c',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'row_min' => 1,
					'row_limit' => 1,
					'layout' => 'row',
					'button_label' => 'Add Row',
					'min' => 0,
					'max' => 0,
					'sub_fields' => array (
						array (
							'key' => 'field_537b9c389bab1',
							'label' => 'Sidebar Name',
							'name' => 'sidebar_name',
							'prefix' => '',
							'type' => 'text',
							'instructions' => 'Displays as a heading for the sidebar',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Upcoming Events',
							'prepend' => '',
							'append' => '',
							'formatting' => 'none',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_537b9c809bab2',
							'label' => 'Button',
							'name' => 'button',
							'prefix' => '',
							'type' => 'true_false',
							'instructions' => 'Display a button link.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => 'Show button',
							'default_value' => 0,
						),
						array (
							'key' => 'field_537ba79d293f4',
							'label' => 'Button Settings',
							'name' => 'button_settings',
							'prefix' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_537b9c809bab2',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'row_min' => 1,
							'row_limit' => 1,
							'layout' => 'row',
							'button_label' => 'Add Row',
							'min' => 0,
							'max' => 0,
							'sub_fields' => array (
								array (
									'key' => 'field_537ba7c3293f5',
									'label' => 'Button Text',
									'name' => 'button_text',
									'prefix' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'formatting' => 'none',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_537ba7e3293f6',
									'label' => 'Button Link',
									'name' => 'button_link',
									'prefix' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => 'http://',
									'prepend' => '',
									'append' => '',
									'formatting' => 'none',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
						),
					),
				),
			),
		),
		array (
			'key' => 'field_537527816e139',
			'label' => 'Page Content',
			'name' => 'page_content',
			'prefix' => '',
			'type' => 'flexible_content',
			'instructions' => 'Main page content.	Sections can be reordered by dragging.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'button_label' => 'Add Row',
			'layouts' => array (
				array (
					'key' => '548b51c24b302',
					'name' => 'story_feed',
					'label' => 'News Story Feed',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_5390b92638513',
							'label' => 'News Feed',
							'name' => '',
							'prefix' => '',
							'type' => 'message',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => 'Stories in the news feed module are populated by the \'<a href="admin.php?page=rss-app">News (RSS)</a>\' app in the left-hand menu.	Stories for one or more RSS feeds can be selected for display within the module.',
						),
						array (
							'key' => 'field_537528bafdef7',
							'label' => 'Section Name',
							'name' => 'section_name',
							'prefix' => '',
							'type' => 'text',
							'instructions' => 'Title displayed on website.	Optional.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'News Stories',
							'prepend' => '',
							'append' => '',
							'formatting' => 'none',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_53760f92d6420',
							'label' => 'Show Date',
							'name' => 'show_date',
							'prefix' => '',
							'type' => 'true_false',
							'instructions' => 'Display the date with each story.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => 'Show date',
							'default_value' => 0,
						),
						array (
							'key' => 'field_53765a76ee58b',
							'label' => 'More News Link',
							'name' => 'more_button',
							'prefix' => '',
							'type' => 'true_false',
							'instructions' => 'Displays a button link at the bottom of this module.	Optional.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => 'Show button',
							'default_value' => 0,
						),
						array (
							'key' => 'field_53765af2fe5ae',
							'label' => 'Button Settings',
							'name' => 'button_settings',
							'prefix' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_53765a76ee58b',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'row_min' => 1,
							'row_limit' => 1,
							'layout' => 'row',
							'button_label' => 'Add Row',
							'min' => 0,
							'max' => 0,
							'sub_fields' => array (
								array (
									'key' => 'field_53765b1afe5af',
									'label' => 'Button Text',
									'name' => 'button_text',
									'prefix' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => 'More Stories',
									'prepend' => '',
									'append' => '',
									'formatting' => 'none',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_53765b46fe5b0',
									'label' => 'Button Link',
									'name' => 'button_link',
									'prefix' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => 'http://',
									'prepend' => '',
									'append' => '',
									'formatting' => 'none',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '548b51c25555a',
					'name' => 'generic_content',
					'label' => 'Announcements and Resources',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_53765525024fa',
							'label' => 'Section Name',
							'name' => 'section_name',
							'prefix' => '',
							'type' => 'text',
							'instructions' => 'Title displayed on website.	Optional.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Resources',
							'prepend' => '',
							'append' => '',
							'formatting' => 'none',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_53765560024fb',
							'label' => 'Content Blocks',
							'name' => 'content_blocks',
							'prefix' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'row_min' => 3,
							'row_limit' => 3,
							'layout' => 'row',
							'button_label' => 'Add Row',
							'min' => 0,
							'max' => 0,
							'sub_fields' => array (
								array (
									'key' => 'field_537655bf024fc',
									'label' => 'Image',
									'name' => 'image',
									'prefix' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'return_format' => 'array',
								),
								array (
									'key' => 'field_5376561d024fd',
									'label' => 'Heading',
									'name' => 'heading',
									'prefix' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => 'Heading',
									'prepend' => '',
									'append' => '',
									'formatting' => 'none',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_5376564a024fe',
									'label' => 'Description',
									'name' => 'description',
									'prefix' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => 'Description',
									'prepend' => '',
									'append' => '',
									'formatting' => 'none',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_5376568f024ff',
									'label' => 'Link To',
									'name' => 'link_to',
									'prefix' => '',
									'type' => 'text',
									'instructions' => 'URL',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => 'http://',
									'prepend' => '',
									'append' => '',
									'formatting' => 'none',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '548b51c25ef2f',
					'name' => 'body_copy',
					'label' => 'Homepage Intro Copy',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_537a1f9e21e86',
							'label' => 'Text',
							'name' => 'text',
							'prefix' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'toolbar' => 'full',
							'media_upload' => 1,
							'tabs' => 'all',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '548b51c260bfd',
					'name' => 'cross-section_content',
					'label' => 'Callout',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_537a24b90bead',
							'label' => 'Text',
							'name' => 'text',
							'prefix' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'toolbar' => 'full',
							'media_upload' => 1,
							'tabs' => 'all',
						),
						array (
							'key' => 'field_537a2704aab47',
							'label' => 'Image',
							'name' => 'image',
							'prefix' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'return_format' => 'array',
						),
						array (
							'key' => 'field_537a24cc0beae',
							'label' => 'Image Position',
							'name' => 'image_position',
							'prefix' => '',
							'type' => 'radio',
							'instructions' => 'Position relative to cross-section text.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'left' => 'Left',
								'right' => 'Right',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'left',
							'layout' => 'vertical',
						),
						array (
							'key' => 'field_537a24f90beaf',
							'label' => 'Link',
							'name' => 'link',
							'prefix' => '',
							'type' => 'true_false',
							'instructions' => 'Do you want this cross section to be a link?',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => 'Make this cross section a link',
							'default_value' => 0,
						),
						array (
							'key' => 'field_538e03a7266ab',
							'label' => 'Link Text',
							'name' => 'link_text',
							'prefix' => '',
							'type' => 'text',
							'instructions' => 'Text to underline when hovering over the cross section',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_537a24f90beaf',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'none',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_537a25830beb0',
							'label' => 'Link To',
							'name' => 'url',
							'prefix' => '',
							'type' => 'text',
							'instructions' => 'Cross section destination URL',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_537a24f90beaf',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'http://',
							'prepend' => '',
							'append' => '',
							'formatting' => 'none',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_537a25b50beb1',
							'label' => 'Background Color',
							'name' => 'background_color',
							'prefix' => '',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'red' => 'Wolfpack Red',
								'reynolds-red' => 'Reynolds Red',
								'orange' => 'Pyroman Flame (orange)',
								'yellow' => 'Hunt Yellow',
								'green' => 'Genomic Green',
								'blue' => 'Innovation Blue',
								'indigo' => 'Bio-indigo',
								'gray-lighter' => '10% Gray',
								'gray-light' => '25% Gray',
								'gray-dark' => '60% Gray',
								'gray-darker' => '90% Gray',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'gray-light',
							'layout' => 'vertical',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '548b51c26b2c2',
					'name' => 'events',
					'label' => 'Events',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_5390b79fd3cc1',
							'label' => 'Calendars',
							'name' => '',
							'prefix' => '',
							'type' => 'message',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => 'Events are auto-populated based upon the <a href="admin.php?page=calendar-app">calendars provided in the left-hand menu</a>.	Individual events can be hidden if desired.',
						),
						array (
							'key' => 'field_537b53dfa9db9',
							'label' => 'Section Name',
							'name' => 'section_name',
							'prefix' => '',
							'type' => 'text',
							'instructions' => 'Title displayed on website.	Optional.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Calendar',
							'prepend' => '',
							'append' => '',
							'formatting' => 'none',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_537b5433a9dba',
							'label' => 'Link to Calendar Page',
							'name' => 'button',
							'prefix' => '',
							'type' => 'true_false',
							'instructions' => 'Display a button link at the bottom of this module.	This is optional.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => 'Show button',
							'default_value' => 0,
						),
						array (
							'key' => 'field_537b5484a9dbb',
							'label' => 'Button Settings',
							'name' => 'button_settings',
							'prefix' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_537b5433a9dba',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'row_min' => 1,
							'row_limit' => 1,
							'layout' => 'row',
							'button_label' => 'Add Row',
							'min' => 0,
							'max' => 0,
							'sub_fields' => array (
								array (
									'key' => 'field_537b54b6a9dbc',
									'label' => 'Button Text',
									'name' => 'button_text',
									'prefix' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'formatting' => 'none',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_537b54d1a9dbd',
									'label' => 'Button Link',
									'name' => 'button_link',
									'prefix' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => 'http://',
									'prepend' => '',
									'append' => '',
									'formatting' => 'none',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '548b51c2744ea',
					'name' => 'social_media',
					'label' => 'Social Media',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_5390b0afec8ae',
							'label' => 'Social Media Accounts',
							'name' => '',
							'prefix' => '',
							'type' => 'message',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => 'This social media module will use the accounts provided in the "NC State Theme Options" at left.	The module is capable of displaying your own Facebook, Twitter, and Instagram content.	Content will only be loaded from the social networks you provide.	It is not necessary to have accounts on all three social networks.',
						),
						array (
							'key' => 'field_537b6b31dd72b',
							'label' => 'Section Name',
							'name' => 'section_name',
							'prefix' => '',
							'type' => 'text',
							'instructions' => 'Title displayed on website.	Optional.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_537b6b39dd72c',
							'label' => 'Button',
							'name' => 'more_button',
							'prefix' => '',
							'type' => 'true_false',
							'instructions' => 'Display a button link at the bottom of this module.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => 'Show button',
							'default_value' => 0,
						),
						array (
							'key' => 'field_537b6b61dd72d',
							'label' => 'Button Settings',
							'name' => 'button_settings',
							'prefix' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'min' => 0,
							'max' => 0,
							'layout' => 'table',
							'button_label' => 'Add Row',
							'sub_fields' => array (
								array (
									'key' => 'field_537b6b85dd72e',
									'label' => 'Button Text',
									'name' => 'button_text',
									'prefix' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'formatting' => 'html',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_537b6b8ddd72f',
									'label' => '',
									'name' => '',
									'prefix' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-home.php',
			),
		),
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-home-split.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
	),
));

register_field_group(array (
	'key' => 'group_548b51c292b4e',
	'title' => 'Metadata',
	'fields' => array (
		array (
			'key' => 'field_536ba962ddb00',
			'label' => 'Custom Metadata?',
			'name' => 'custom_metadata',
			'prefix' => '',
			'type' => 'radio',
			'instructions' => 'Information for search engines and social media sharing.	By default each page uses the site-wide metadata set in "NC State Theme Options."
<br /><br />
\'Yes\' will allow you to customize that information for this specific page.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'true' => 'Yes',
				'false' => 'No',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'false',
			'layout' => 'horizontal',
		),
		array (
			'key' => 'field_536ba953ddaff',
			'label' => 'Search Engine Description',
			'name' => 'search_engine_description',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_536ba962ddb00',
						'operator' => '==',
						'value' => 'true',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_536ba98c89af7',
			'label' => 'Social Media Title',
			'name' => 'social_media_title',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_536ba962ddb00',
						'operator' => '==',
						'value' => 'true',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_536ba99789af8',
			'label' => 'Social Media Description',
			'name' => 'social_media_description',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_536ba962ddb00',
						'operator' => '==',
						'value' => 'true',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_536ba9a289af9',
			'label' => 'Social Media Image',
			'name' => 'social_media_image',
			'prefix' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_536ba962ddb00',
						'operator' => '==',
						'value' => 'true',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'return_format' => 'url',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 100,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
	),
));

endif;