<?php
	register_field_group(array (
		'id' => 'acf_text-page',
		'title' => 'Text Page',
		'fields' => array (
			array (
				'key' => 'field_5399b452de928',
				'label' => 'Template Information',
				'name' => '',
				'type' => 'message',
				'message' => 'Click \'Add Row\' below to add content to your page.	You may choose from body copy or a callout.	Each content type can be repeated as many times as needed.',
			),
			array (
				'key' => 'field_5363da3a05321',
				'label' => 'Page Content',
				'name' => 'page_content',
				'type' => 'flexible_content',
				'layouts' => array (
					array (
						'label' => 'Body Copy',
						'name' => 'body_copy',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_5363da7f05322',
								'label' => 'Text',
								'name' => 'text',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
						),
					),
					array (
						'label' => 'Callout',
						'name' => 'cross-section_content',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_5363da9c05324',
								'label' => 'Text',
								'name' => 'text',
								'type' => 'wysiwyg',
								'instructions' => 'Pay close attention to the length of your text. If you put too much, it will get cut off.',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
							array (
								'key' => 'field_5363daa405325',
								'label' => 'Image',
								'name' => 'image',
								'type' => 'image',
								'instructions' => 'Dimensions: 768x432px.',
								'required' => 1,
								'column_width' => '',
								'save_format' => 'object',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_5363daaf05326',
								'label' => 'Image Position',
								'name' => 'image_position',
								'type' => 'radio',
								'instructions' => 'Position relative to callout text.	If the left side of your image is more important, chose left. If the right is more important, chose right.',
								'column_width' => '',
								'choices' => array (
									'left' => 'Left',
									'right' => 'Right',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'left',
								'layout' => 'vertical',
							),
							array (
								'key' => 'field_5369077d2256a',
								'label' => 'Link',
								'name' => 'link',
								'type' => 'true_false',
								'instructions' => 'Do you want this callout to be a link?',
								'column_width' => '',
								'message' => 'Make this callout a link',
								'default_value' => 0,
							),
							array (
								'key' => 'field_538e071ca557d',
								'label' => 'Link Text',
								'name' => 'link_text',
								'type' => 'text',
								'instructions' => 'Text to underline when hovering over the callout',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_5369077d2256a',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => 20,
							),
							array (
								'key' => 'field_5368f6e70455a',
								'label' => 'Link To',
								'name' => 'url',
								'type' => 'text',
								'instructions' => 'Callout\'s destination URL',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_5369077d2256a',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'default_value' => '',
								'placeholder' => 'http://',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5369447827dd6',
								'label' => 'Background Color',
								'name' => 'background_color',
								'type' => 'radio',
								'column_width' => '',
								'choices' => array (
									'red' => 'Wolfpack Red',
									'reynolds-red' => 'Reynolds Red',
									'orange' => 'Pyroman Flame (orange)',
									'yellow' => 'Hunt Yellow',
									'green' => 'Genomic Green',
									'blue' => 'Innovation Blue',
									'indigo' => 'Bio-indigo',
									'gray-lighter' => '10% Gray',
									'gray-light' => '25% Gray',
									'gray-dark' => '60% Gray',
									'gray-darker' => '90% Gray',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'blue',
								'layout' => 'vertical',
							),
						),
					),
				),
				'button_label' => 'Add Row',
				'min' => '',
				'max' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
					'order_no' => 0,
					'group_no' => 0,
				),
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-nav.php',
					'order_no' => 1,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'default',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'featured_image',
			),
		),
		'menu_order' => 0,
	));