<?php

if( function_exists('register_field_group') ):

register_field_group(array (
	'key' => 'group_548b51c27ee44',
	'title' => 'Section Description',
	'fields' => array (
		array (
			'key' => 'field_536b9116f8339',
			'label' => 'Page Description',
			'name' => 'section_description',
			'prefix' => '',
			'type' => 'text',
			'instructions' => 'Optional text that will appear below the page\'s title within the gray box.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'top_level',
			),
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'default',
			),
		),
		array (
			array (
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'top_level',
			),
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
	),
));

register_field_group(array (
	'key' => 'group_548b51c282347',
	'title' => 'Text Page',
	'fields' => array (
		array (
			'key' => 'field_5363da3a05321',
			'label' => 'Page Content',
			'name' => 'page_content',
			'prefix' => '',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Add Row',
			'min' => '',
			'max' => '',
			'layouts' => array (
				array (
					'key' => '548b51c285bfd',
					'name' => 'body_copy',
					'label' => 'Body Copy',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_5363da7f05322',
							'label' => 'Text',
							'name' => 'text',
							'prefix' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'toolbar' => 'full',
							'media_upload' => 1,
							'tabs' => 'all',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '548b51c2872ca',
					'name' => 'cross-section_content',
					'label' => 'Callout',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_5363da9c05324',
							'label' => 'Text',
							'name' => 'text',
							'prefix' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'toolbar' => 'full',
							'media_upload' => 1,
							'tabs' => 'all',
						),
						array (
							'key' => 'field_5363daa405325',
							'label' => 'Image',
							'name' => 'image',
							'prefix' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'return_format' => 'array',
						),
						array (
							'key' => 'field_5363daaf05326',
							'label' => 'Image Position',
							'name' => 'image_position',
							'prefix' => '',
							'type' => 'radio',
							'instructions' => 'Position relative to cross-section text.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'left' => 'Left',
								'right' => 'Right',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'left',
							'layout' => 'vertical',
						),
						array (
							'key' => 'field_5369077d2256a',
							'label' => 'Link',
							'name' => 'link',
							'prefix' => '',
							'type' => 'true_false',
							'instructions' => 'Do you want this cross section to be a link?',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => 'Make this cross section a link',
							'default_value' => 0,
						),
						array (
							'key' => 'field_538e071ca557d',
							'label' => 'Link Text',
							'name' => 'link_text',
							'prefix' => '',
							'type' => 'text',
							'instructions' => 'Text to underline when hovering over the cross section',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5369077d2256a',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'none',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_5368f6e70455a',
							'label' => 'Link To',
							'name' => 'url',
							'prefix' => '',
							'type' => 'text',
							'instructions' => 'Cross section destination URL',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5369077d2256a',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'http://',
							'prepend' => '',
							'append' => '',
							'formatting' => 'none',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_5369447827dd6',
							'label' => 'Background Color',
							'name' => 'background_color',
							'prefix' => '',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'red' => 'Wolfpack Red',
								'reynolds-red' => 'Reynolds Red',
								'orange' => 'Pyroman Flame (orange)',
								'yellow' => 'Hunt Yellow',
								'green' => 'Genomic Green',
								'blue' => 'Innovation Blue',
								'indigo' => 'Bio-indigo',
								'gray-lighter' => '10% Gray',
								'gray-light' => '25% Gray',
								'gray-dark' => '60% Gray',
								'gray-darker' => '90% Gray',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'blue',
							'layout' => 'vertical',
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'default',
			),
		),
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-text.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
	),
));

endif;